<a href="https://colab.research.google.com/github/rpranav07/AI_Research/blob/rpranav07-patch-1/Numpy(01).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### What is Numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays
1D , 2D , 3D ,arange , arange with reshape , dtype , ones ,zeros , identity , linspace  ,random

In [59]:
# np.array
import numpy as np
# 1D Array :- Vectors
a = np.array([1,2,3])
print(a)

[1 2 3]


In [60]:
# 2D  Array :- Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [61]:
#3D Array :- Tensors
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [62]:
# dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [63]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [64]:
np.arange(1,13).reshape(2,2,3)


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [65]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [66]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [67]:
# np.ones and np.zeros
np.ones((2,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [68]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [69]:
# np.random
np.random.random((3,4))

array([[0.62588524, 0.53101981, 0.53580333, 0.60628435],
       [0.55365731, 0.05298291, 0.86236411, 0.88052892],
       [0.23470518, 0.31011233, 0.38419613, 0.99862888]])

In [70]:
# np.linspace
x=np.linspace(-10,10,10,dtype=int)
print(x)
y=np.linspace(-10,10,10,dtype=float)
print(y)

[-10  -8  -6  -4  -2   1   3   5   7  10]
[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [71]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes
ndim  ,  shape  ,  size   ,  itemsize   ,  dtype

In [72]:
a1 = np.arange(10,dtype=np.int8)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)


[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [73]:
# ndim
print(a1.ndim)
print(a3.ndim)
print(a2.ndim)


1
3
2


In [74]:
# shape
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [75]:
# size  :-  No of elements
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [76]:
# itemsize:- in colab item size of float64 and int64 is same (8) but different in pycharm item size of int64 and int 32 is different
print(a1.itemsize)
print(a2.itemsize)
a3.itemsize

1
8


8

In [77]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int8
float64
int64


### Changing Datatype

In [78]:
# astype
a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [79]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(a1)

a2

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [80]:
# scalar operations
# a1+2 ,a1-8 ,a1*7, a1\5
# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [81]:
# relational
print(a2>15)
a2 == 15
#print(a2[0,3])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
15


In [82]:
# vector operations
# arithmetic
# a1 + a2 , a1-a2 , a1*a2 , a1/a2

print(a1*a2) #multiply respective position element
a1 ** a2

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions
round  ,  max  ,   min   ,  prod   (axis wise)    , mean   ,   median  ,  std  ,  var  ,   trignomrtry  ,   floor  ,  ceil  ,   log  ,  expo  ,   dot

In [83]:
a1 = np.random.random((3,3))
print(a1)
a2 = np.round(a1*100)
print(a2)
a3 = np.round(a1)
print(a3)
#a4 = np.ceil(a2)
#print(a4)
#a5 = np.floor(a2)
#print(a5)

[[0.62981095 0.205591   0.75067441]
 [0.73592556 0.76506814 0.66411619]
 [0.91889766 0.80093925 0.81686618]]
[[63. 21. 75.]
 [74. 77. 66.]
 [92. 80. 82.]]
[[1. 0. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [84]:
# max/min/sum/prod
print(a1)
print(np.min(a1))
print(np.sum(a1))
print(np.prod(a1))

[[0.62981095 0.205591   0.75067441]
 [0.73592556 0.76506814 0.66411619]
 [0.91889766 0.80093925 0.81686618]]
0.20559099530671787
6.287889339150774
0.021850512083945995


In [85]:
# 0 -> col and 1 -> row
print(np.sum(a1,axis=0))
print(np.max(a1,axis=0))
print(np.min(a1,axis=0))
print(np.prod(a1,axis=0))
print(np.sum(a1,axis=1))
print(np.max(a1,axis=1))
print(np.min(a1,axis=1))
print(np.prod(a1,axis=1))

[2.28463417 1.77159839 2.23165678]
[0.91889766 0.80093925 0.81686618]
[0.62981095 0.205591   0.66411619]
[0.42590353 0.12598063 0.4072364 ]
[1.58607635 2.16510989 2.53670309]
[0.75067441 0.76506814 0.91889766]
[0.205591   0.66411619 0.80093925]
[0.09719992 0.37391946 0.60119816]


In [86]:
# mean/median/std/var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

0.6986543710167527
0.7506744085227685
0.1916284437738701
0.036721460463195285


In [87]:
print(np.mean(a1,axis=0))
print(np.std(a1,axis=1))
np.var(a1,axis=1)

[0.76154472 0.5905328  0.74388559]
[0.23373453 0.04242271 0.0522582 ]


array([0.05463183, 0.00179969, 0.00273092])

In [88]:
# trigonomoetric functions(sin ,cos ,tan , cot , cosec , sec)
np.sin(a1)

array([[0.58899199, 0.20414574, 0.68213206],
       [0.67127348, 0.69258615, 0.61636341],
       [0.79493331, 0.71801016, 0.72900428]])

In [89]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [90]:
# log and exponents
print(np.log(a1))
np.exp(a1)

[[-0.46233558 -1.58186654 -0.28678327]
 [-0.30662631 -0.26779037 -0.40929816]
 [-0.08458053 -0.22197017 -0.20227999]]


array([[1.87725565, 1.22825074, 2.11842822],
       [2.08741313, 2.14914082, 1.94277272],
       [2.50652581, 2.22763226, 2.26339564]])

In [91]:
# round/floor/ceil
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))

np.ceil(np.random.random((2,3))*100)

[[49. 82. 95.]
 [26. 30. 23.]]
[[51. 15. 70.]
 [19. 47. 70.]]


array([[35., 58., 36.],
       [47., 21., 54.]])

### Indexing and Slicing

In [92]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [93]:
#Indexing
print(a1[2])
print(a2[1,2])
print(a3[1,0,1])
print(a3[1,1,0])
print(a3[-1,-2,-2])

2
6
5
6
4


In [94]:
#Slicing
# Slicing in 1D
print(a1[2:5])
print(a1[2:7:2])


[2 3 4]
[2 4 6]


In [95]:
a2  # for slicing in 2D array first slice the row then , then slice the column

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [119]:
# for slicing in 2D array first slice the row then , then slice the column
print(a2[0:2,1::2])
print(a2[::2,1::2])
print(a2[1,::3])
print(a2[1:,::3])
print(a2[0,:])
print(a2[:,2])
print(a2[::2 , ::3])

[[1 3]
 [5 7]]
[[ 1  3]
 [ 9 11]]
[4 7]
[[ 4  7]
 [ 8 11]]
[0 1 2 3]
[ 2  6 10]
[[ 0  3]
 [ 8 11]]


In [97]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [98]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [99]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [100]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [101]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [123]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [103]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [105]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [107]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [108]:
# reshape

In [109]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [110]:
# ravel
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [111]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [112]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [113]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [114]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [130]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [132]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]